### ISSUE TITLE
Which properties in the YAML file must be updated to change the Kafka replication factor?

### ISSUE THREAD

**Issue by emmanuelbernard** [debezium/microservices-lab#38]
I see

```
 kafka:                                                                                                                                                                             
    config:                                                                                                                                                                           
      offsets.topic.replication.factor: 3                                                                                                                                             
      transaction.state.log.min.isr: 2                                                                                                                                                
      transaction.state.log.replication.factor: 3                                                                                                                                     
```

Which one?
